### ISSUE TITLE
Check value for X_WF_VSLIDE2

### ISSUE THREAD

**Issue by th-otto** [freemint/gemlib#20]
The value for X_WF_VSLIDE2 (geneva) is identical to that of X_WF_VSPLIT. Is that correct?

**Comment by xdelatour** [comment]
No,

- X_WF_VSLIDE2 (0x1B00)
- X_WF_VSPLIT (0x1800)

https://taflee.tripod.com/gnva.html

**Comment by th-otto** [comment]
Thanks, fixed now.

Do you now where the definitions of X_WF_DIALEDIT and X_WF_DCOLSTAT come from? I can't find them in that document. I think that X_WF_DIALEDIT is also wrong (would make sense to be 8192 = 0x2000 instead of 9182)

**Comment by xdelatour** [comment]
Yes, I can confirm X_WF_DIALEDIT is 0x2000: doc available [here](https://taflee.tripod.com/gnvc.html).
No information about X_WF_DCOLSTAT though

[EDIT] Found in gnva006a.zip (patch from 005 to 006): 
[XWIND.H.TXT](https://github.com/freemint/gemlib/files/10565505/XWIND.H.TXT)

**Comment by th-otto** [comment]
Fixed by 2c625ea747bff77aa368d7e2a5acc230538f54eb
