### ISSUE TITLE
'lib' project isn't possible to build with make -j

### ISSUE THREAD

**Issue by mikrosk** [freemint/gemlib#6]
What is really awkward as there's basically heaps of opportunities -- both `gemma` and `cflib` depend on `gemlib` so these can be build in parallel plus all the CPU/mshort variants as well.

**Comment by th-otto** [comment]
That dependency is exactly the reason why make -j does not work from the toplevel Makefile. make will build all 3 directories in parallel, but some of the demo/test apps need gemlib to be build first. Another reason is that the RULES descent into the sub-directories (where the demos are built) before their own library is finished.

BTW. it would make IMHO sense to split these 3 libraries into 3 different repos. Creating packages for them is otherwise a pain.

**Comment by mikrosk** [comment]
I'm not against the idea of splitting either. 'lib' has always sounded a bit stupid to me and gemlib, as the most important building stone, definitely deserves it.

**Comment by th-otto** [comment]
Should be fixed now by https://github.com/freemint/lib/commit/ad0691f767ac9a633860ddb7c1f2e4a272583fce

For splitting the repos, i thought of

- create 2 copies of this repo, one for cflib, another for libgemma
- remove sources of gemlib & libgemma from copy of cflib
- remove sources of gemlib & cflib from copy of libgemma
- reorganize Makefiles accordingly
- rename this repo to gemlib

This should make sure the git history is preserved in all new repos.

**Comment by mikrosk** [comment]
OK, I'm working on it. Please don't commit anything to this repository until further notice. :)

**Comment by th-otto** [comment]
Nice. Let me know if you need any help with it.

**Comment by mikrosk** [comment]
cflib: https://github.com/freemint/cflib (incl. travis)

**Comment by mikrosk** [comment]
gemma: https://github.com/freemint/gemma (incl. travis but compilation fails on some mysterious error I'm unable to replicate locally)

**Comment by mikrosk** [comment]
... and done! This repository has been renamed to `gemlib`, website updated too.

There seems to be a quirk in Travis, even after renaming `lib` to `gemlib` it still insists on ${TRAVIS_REPO_SLUG} being still `lib`. Hopefully it will learn in time. ;)

**Comment by th-otto** [comment]
>There seems to be a quirk in Travis, even after renaming lib to gemlib it still insists on >${TRAVIS_REPO_SLUG} being still lib. Hopefully it will learn in time. ;)

Could be caching on travis side. Maybe this will be fixed tomorrow, if not try going to your travis profile page and use "Sync account"

**Comment by th-otto** [comment]
> incl. travis but compilation fails on some mysterious error I'm unable to replicate locally)

see https://travis-ci.org/freemint/gemma/builds/404516858#L967

I think this is because the gemlib installed from launchpad is slightly older. We could fix that here, or just wait until the packages has been updated.

**Comment by mikrosk** [comment]
Ah, right. I couldn't understand why I see the constant in my headers and everything and it's failing on Travis. I guess @vinriviere is going to update everything anyway, so let's wait.

**Comment by vinriviere** [comment]
> see https://travis-ci.org/freemint/gemma/builds/404516858#L967
>
> I think this is because the gemlib installed from launchpad is slightly older. We could fix that here, or just wait until the packages has been updated.

Wow. I hit the same issue: WF_WIND_ATTACH undeclared. And I never hit that on my local Cygwin.
Reason is that in 2017, I updated the GEMlib package in Cygwin binaries, and I forgot to update Ubuntu packages.
Fixed.
I will upgrade everything later.
